music_directory "/var/lib/mpd/music"
playlist_directory "/var/lib/mpd/playlists"

db_file "/var/lib/mpd/tag_cache"
state_file "/var/lib/mpd/state"
sticker_file "/var/lib/mpd/sticker.sql"

log_file "/dev/stdout"

bind_to_address "0.0.0.0"
port "6600"

audio_output {
    type "alsa"
    name "ALSA Output"
    device "default"
    mixer_type "software"
}

filesystem_charset "UTF-8"